baseurl = "https://esfand-r.github.io/esfand-r.github.com/"
title = "Divine Comedy of a Software Engineer"
languageCode = "en-us"
theme = "internet-weblog"
SectionPagesMenu = "main"
Paginate = 10
pygmentsstyle = "emacs"

[params]
	Description = "I hope you find this interesting."
	ShowCopyright = true
	RSSEnabled = true
	RSSSections = [ "Posts", "Microposts" ]

[taxonomies]
  	tag = "tags"
  	category = "categories"
  	series = "series"

		[author]
			Handle = "esfandiar"
			FirstName = "Esfandiar"
			LastName = "Amirrahimi"
			AboutPage = "/about"
			Location = "Montreal, QC"

[[menu.main]]
      name = "Posts"
      weight = 1
    	identifier = "posts"
      url = "/posts/"

[[menu.main]]
    	name = "Microposts"
    	weight = 2
    	identifier = "microposts"
    	url = "/microposts/"

[[menu.main]]
    	name = "Photos"
    	weight = 3
    	identifier = "photos"
    	url = "/photos/"
